"""
This type stub file was generated by pyright.
"""

from typing import Optional

class SimpleCookieJar:
    def __init__(self) -> None:
        ...
    
    def add(self, set_cookie: Optional[str]) -> None:
        ...
    
    def set(self, set_cookie: str) -> None:
        ...
    
    def get(self, host: str) -> str:
        ...
    


