"""
This type stub file was generated by pyright.
"""

import logging

_logger = ...
_traceEnabled = ...
__all__ = ["enableTrace", "dump", "error", "warning", "debug", "trace", "isEnabledForError", "isEnabledForDebug", "isEnabledForTrace"]
def enableTrace(traceable: bool, handler: logging.StreamHandler = ..., level: str = ...) -> None:
    """
    Turn on/off the traceability.

    Parameters
    ----------
    traceable: bool
        If set to True, traceability is enabled.
    """
    ...

def dump(title: str, message: str) -> None:
    ...

def error(msg: str) -> None:
    ...

def warning(msg: str) -> None:
    ...

def debug(msg: str) -> None:
    ...

def info(msg: str) -> None:
    ...

def trace(msg: str) -> None:
    ...

def isEnabledForError() -> bool:
    ...

def isEnabledForDebug() -> bool:
    ...

def isEnabledForTrace() -> bool:
    ...

