"""
This type stub file was generated by pyright.
"""

from typing import Union

__all__ = ["NoLock", "validate_utf8", "extract_err_message", "extract_error_code"]
class NoLock:
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback) -> None:
        ...
    


def validate_utf8(utfbytes: Union[str, bytes]) -> bool:
    """
    validate utf8 byte string.
    utfbytes: utf byte string to check.
    return value: if valid utf8 string, return true. Otherwise, return false.
    """
    ...

def extract_err_message(exception: Exception) -> Union[str, None]:
    ...

def extract_error_code(exception: Exception) -> Union[int, None]:
    ...

